[server]
port = 8501

[logger]
level="error"

[client]
showErrorDetails = true

[theme]
primaryColor="#38bcf0"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#f2f2f7"
textColor="#262730"
font="sans serif"
